---
# MariaDB server
- name: Install MariaDB package
  yum:
    name: mariadb-server
    state: installed
  become: yes

- name: Start Mysql Service
  service:
    name: mariadb
    state: started
    enabled: yes
  become: yes

# TODO: any conf changes needed for dev?