---
# Set up webserver-y things

# TODO: select dev/prod environment file as needed
- name: set up env vars
  copy:
    src: environment.{{type}}
    dest: /etc/environment
  become: yes

- name: install php7
  shell: amazon-linux-extras install php7.2 -y
  become: yes

- name: Install apache
  yum:
    name: httpd
    state: latest
  become: yes

- name: Install apache config
  template:
    src: httpd.conf.j2
    dest: /etc/httpd/conf/httpd.conf
  become: yes

- name: Create vhosts config dir
  file:
    path: /etc/httpd/conf/vhosts.d
    state: directory
  become: yes

- name: Fix webroot perms
  file:
    recurse: yes
    path: /var/www
    owner: ec2-user
    group: apache
    mode: '2775'
  become: yes

- name: Create vhost dir
  file:
    path: /var/www/vhosts/default
    state: directory

- name: Remove old default webroot
  file:
    path: /var/www/html
    state: absent

- name: Start/enable apache
  service:
    name: httpd
    state: started
    enabled: yes
  become: yes

- name: Assign ec2-user to apache group
  shell: usermod -a -G apache ec2-user
  become: yes

- name: Install composer
  script: install-composer.sh
  become: yes